Ticket-8
ThePotato97/fe-nc-news pull request #6
Opened 2023-06-01 14:25 UTC by ThePotato97

2023-06-01 15:05 UTC, MRombi requested changes
Very good job on this ticket, just a few changes are needed. Please, resubmit once you have actioned on the given feedback 🙂

2023-06-01 15:05 UTC, MRombi commented on src/components/Comments.jsx
> +    const username = e.target.username.value;
Users should not be allowed to post as anybody else. We should have a user system. It can be hard coded 🙂

2023-06-01 15:05 UTC, MRombi commented on src/components/Comments.jsx
> +    const comment = e.target.comment.value;
The field of the form should be cleared after a comment has been posted 🙂

2023-06-02 08:20 UTC, JVal-NC commented
Chris, good work. User feedback  for successful / unsuccessful posts is really clean.

Go ahead and merge.

2023-06-02 09:14 UTC, merged